build DEB package (#3)
- Update .gitignore
- Add debian/ folder with specific deb-package files
- Update build-in-docker scripts
- Add dev/detect-gphome.bash script
- Add Makefile targets for deb-package build
- Update CI upload build/deb artifacts

diff --git a/.github/workflows/greengage-ci.yml b/.github/workflows/greengage-ci.yml
--- a/.github/workflows/greengage-ci.yml
+++ b/.github/workflows/greengage-ci.yml
@@ -14,8 +14,8 @@ concurrency:
 
 env:
   DEV_HOME: /home/gpadmin
-  PXF_HOME: /usr/local/greengage-db-devel/pxf
-  GPHOME:   /usr/local/greengage-db-devel
+  PXF_HOME: /opt/greengagedb/greengage/pxf
+  GPHOME:   /opt/greengagedb/greengage
   GOPATH:   /opt/go
 
 jobs:
@@ -26,18 +26,18 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          - image: greengagedb/ggdb6_ubuntu:6.29.1
-            release: stable
-            version: '6'
+          # - image: greengagedb/ggdb6_ubuntu:6.29.1
+          #   release: stable
+          #   version: '6'
           - image: ghcr.io/greengagedb/greengage/ggdb6_ubuntu
             release: devel
             version: '6'
-          - image: greengagedb/ggdb7_ubuntu:7.4.0
-            release: stable
-            version: '7'
-          - image: ghcr.io/greengagedb/greengage/ggdb7_ubuntu
-            release: devel
-            version: '7'
+          # - image: greengagedb/ggdb7_ubuntu:7.4.0
+          #   release: stable
+          #   version: '7'
+          # - image: ghcr.io/greengagedb/greengage/ggdb7_ubuntu
+          #   release: devel
+          #   version: '7'
 
     container:
       image: ${{ matrix.image }}
@@ -52,6 +52,8 @@ jobs:
         PATH: ${{ env.GPHOME }}/bin:${{ env.PXF_HOME }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:${{ env.GOPATH }}/bin
         JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
         DEBIAN_FRONTEND: noninteractive
+        GREENGAGE_DEB: /tmp/greengage.deb
+        GREENGAGE_DEB_URL: https://github.com/magf/greengage/releases/download/6.99.9/greengage6.deb
     steps:
       - uses: actions/checkout@v4
       - name: Build in Docker
@@ -61,148 +63,191 @@ jobs:
           cd $PXF_SRC
           bash ci/build_in_docker.sh
           git config --global --add safe.directory $PXF_SRC
-          # make deb
-      # - name: Cache deb packages
-      #   uses: actions/cache@v4
-      #   with:
-      #     path: build/*.deb
-      #     key: pxf-deb-${{ github.sha }}-${{ matrix.version }}-${{ matrix.release }}
-      # - name: Upload build artifacts
+      - name: Cache packages
+        uses: actions/cache@v4
+        with:
+          path: Package/
+          key: pxf-packages-${{ github.sha }}-${{ matrix.version }}-${{ matrix.release }}
+      - name: Upload package artifacts
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: pxf-packages-${{ matrix.version }}-${{ matrix.release }}
+          path: Package/
+      # - name: Upload debian artifacts
       #   if: always()
       #   uses: actions/upload-artifact@v4
       #   with:
-      #     name: pxf-deb-${{ matrix.version }}-${{ matrix.release }}
-      #     path: build/*.deb
+      #     name: pxf-debian-${{ matrix.version }}-${{ matrix.release }}
+      #     path: debian/tmp/pxf/
+      # - name: Upload build server logs
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: pxf-build-server-logs-${{ matrix.version }}-${{ matrix.release }}
+      #     path: /home/gpadmin/pxf/server/pxf-service/build/reports
 
-  regression:
-    name: Regression on ggdb${{ matrix.version }}-${{ matrix.release }}
+  # regression:
+  #   name: Regression on ggdb${{ matrix.version }}-${{ matrix.release }}
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 180
+
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - image: greengagedb/ggdb6_ubuntu:6.29.1
+  #           release: stable
+  #           version: '6'
+  #         - image: ghcr.io/greengagedb/greengage/ggdb6_ubuntu
+  #           release: devel
+  #           version: '6'
+  #         - image: greengagedb/ggdb7_ubuntu:7.4.0
+  #           release: stable
+  #           version: '7'
+  #         - image: ghcr.io/greengagedb/greengage/ggdb7_ubuntu
+  #           release: devel
+  #           version: '7'
+
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Build PXF regression on ggdb${{ matrix.version }}-${{ matrix.release }} 
+  #       uses: docker/build-push-action@v6
+  #       with:
+  #         context: .
+  #         file: ./ci/Dockerfile.${{ github.job }}
+  #         push: false
+  #         tags: greengagedb/ggdb${{ matrix.version }}_pxf_regression:${{ matrix.release }}
+  #         build-args: GGDB_IMAGE=${{ matrix.image }}
+
+  #     - name: Run regression on ggdb${{ matrix.version }}-${{ matrix.release }}
+  #       shell: bash
+  #       run: |
+  #         mkdir logs
+  #         docker run --user root:root \
+  #           -v ./logs:/logs \
+  #           --sysctl 'kernel.sem=500 1024000 200 4096' \
+  #           --privileged \
+  #           greengagedb/ggdb${{ matrix.version }}_pxf_regression:${{ matrix.release }} \
+  #           bash -c "
+  #             set +e
+  #             cd /tmp/build || status=1
+  #             pxf_src/ci/test_in_docker.sh
+  #             status=\$?
+  #             find /tmp/build/pxf_src/fdw -type f -name *.diffs -exec mv -f {} /logs \;
+  #             echo \">>> STATUS \$status\"
+  #             exit \${status:-1}
+  #           "
+
+  #     - name: Upload regression artifacts
+  #       if: always()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: regression-ggdb${{ matrix.version }}-${{ matrix.release }}
+  #         path: logs
+  #         retention-days: 7
+  #         if-no-files-found: warn
+
+  # integration-ggdb6-stable:
+  #   name: Integration on ggdb6-stable
+  #   uses: ./.github/workflows/integration-tests.yml
+  #   with:
+  #     image: greengagedb/ggdb6_ubuntu:6.29.1
+  #     version: '6'
+  #     release: stable
+  #     tests_matrix: |
+  #       [
+  #         { "test": "smoke" },
+  #         { "test": "gpdb" },
+  #         { "test": "jdbc" },
+  #         { "test": "smoke", "fdw": "true" },
+  #         { "test": "gpdb", "fdw": "true" },
+  #         { "test": "jdbc", "fdw": "true" },
+  #         { "test": "ggdbssl", "fdw": "true", "ssl": "true" }
+  #       ]
+
+  # integration-ggdb6-devel:
+  #   name: Integration on ggdb6-devel
+  #   uses: ./.github/workflows/integration-tests.yml
+  #   with:
+  #     image: ghcr.io/greengagedb/greengage/ggdb6_ubuntu
+  #     version: '6'
+  #     release: devel
+  #     tests_matrix: |
+  #       [
+  #         { "test": "smoke" },
+  #         { "test": "gpdb" },
+  #         { "test": "jdbc" },
+  #         { "test": "smoke", "fdw": "true" },
+  #         { "test": "gpdb", "fdw": "true" },
+  #         { "test": "jdbc", "fdw": "true" },
+  #         { "test": "ggdbssl", "fdw": "true", "ssl": "true" }
+  #       ]
+
+  # integration-ggdb7-stable:
+  #   name: Integration on ggdb7-stable
+  #   uses: ./.github/workflows/integration-tests.yml
+  #   with:
+  #     image: greengagedb/ggdb7_ubuntu:7.4.0
+  #     version: '7'
+  #     release: stable
+  #     tests_matrix: |
+  #       [
+  #         { "test": "smoke" },
+  #         { "test": "gpdb" },
+  #         { "test": "jdbc" },
+  #         { "test": "smoke", "fdw": "true" },
+  #         { "test": "gpdb", "fdw": "true" },
+  #         { "test": "jdbc", "fdw": "true" },
+  #         { "test": "ggdbssl", "fdw": "true", "ssl": "true" }
+  #       ]
+
+  # integration-ggdb7-devel:
+  #   name: Integration on ggdb7-devel
+  #   uses: ./.github/workflows/integration-tests.yml
+  #   with:
+  #     image: ghcr.io/greengagedb/greengage/ggdb7_ubuntu
+  #     version: '7'
+  #     release: devel
+  #     tests_matrix: |
+  #       [
+  #         { "test": "smoke" },
+  #         { "test": "gpdb" },
+  #         { "test": "jdbc" },
+  #         { "test": "smoke", "fdw": "true" },
+  #         { "test": "gpdb", "fdw": "true" },
+  #         { "test": "jdbc", "fdw": "true" },
+  #         { "test": "ggdbssl", "fdw": "true", "ssl": "true" }
+  #       ]
+
+  upload-to-release:
+    if: startsWith(github.ref, 'refs/tags/')
+    needs: [build]
     runs-on: ubuntu-latest
-    timeout-minutes: 180
-
     strategy:
       fail-fast: false
       matrix:
         include:
-          - image: greengagedb/ggdb6_ubuntu:6.29.1
-            release: stable
-            version: '6'
+          # - image: greengagedb/ggdb6_ubuntu:6.29.1
+          #   release: stable
+          #   version: '6'
           - image: ghcr.io/greengagedb/greengage/ggdb6_ubuntu
             release: devel
             version: '6'
-          - image: greengagedb/ggdb7_ubuntu:7.4.0
-            release: stable
-            version: '7'
-          - image: ghcr.io/greengagedb/greengage/ggdb7_ubuntu
-            release: devel
-            version: '7'
-
+          # - image: greengagedb/ggdb7_ubuntu:7.4.0
+          #   release: stable
+          #   version: '7'
+          # - image: ghcr.io/greengagedb/greengage/ggdb7_ubuntu
+          #   release: devel
+          #   version: '7'
+    permissions:
+      contents: write  # Required for release creation
     steps:
-      - uses: actions/checkout@v4
-      - name: Build PXF regression on ggdb${{ matrix.version }}-${{ matrix.release }} 
-        uses: docker/build-push-action@v6
+      - name: Upload packages to release
+        uses: greengagedb/greengage-ci/.github/actions/upload-pkgs-to-release@ADBDEV-8877
         with:
-          context: .
-          file: ./ci/Dockerfile.${{ github.job }}
-          push: false
-          tags: greengagedb/ggdb${{ matrix.version }}_pxf_regression:${{ matrix.release }}
-          build-args: GGDB_IMAGE=${{ matrix.image }}
-
-      - name: Run regression on ggdb${{ matrix.version }}-${{ matrix.release }}
-        shell: bash
-        run: |
-          mkdir logs
-          docker run --user root:root \
-            -v ./logs:/logs \
-            --sysctl 'kernel.sem=500 1024000 200 4096' \
-            --privileged \
-            greengagedb/ggdb${{ matrix.version }}_pxf_regression:${{ matrix.release }} \
-            bash -c "
-              set +e
-              cd /tmp/build || status=1
-              pxf_src/ci/test_in_docker.sh
-              status=\$?
-              find /tmp/build/pxf_src/fdw -type f -name *.diffs -exec mv -f {} /logs \;
-              echo \">>> STATUS \$status\"
-              exit \${status:-1}
-            "
-
-      - name: Upload regression artifacts
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: regression-ggdb${{ matrix.version }}-${{ matrix.release }}
-          path: logs
-          retention-days: 7
-          if-no-files-found: warn
-
-  integration-ggdb6-stable:
-    name: Integration on ggdb6-stable
-    uses: ./.github/workflows/integration-tests.yml
-    with:
-      image: greengagedb/ggdb6_ubuntu:6.29.1
-      version: '6'
-      release: stable
-      tests_matrix: |
-        [
-          { "test": "smoke" },
-          { "test": "gpdb" },
-          { "test": "jdbc" },
-          { "test": "smoke", "fdw": "true" },
-          { "test": "gpdb", "fdw": "true" },
-          { "test": "jdbc", "fdw": "true" },
-          { "test": "ggdbssl", "fdw": "true", "ssl": "true" }
-        ]
-
-  integration-ggdb6-devel:
-    name: Integration on ggdb6-devel
-    uses: ./.github/workflows/integration-tests.yml
-    with:
-      image: ghcr.io/greengagedb/greengage/ggdb6_ubuntu
-      version: '6'
-      release: devel
-      tests_matrix: |
-        [
-          { "test": "smoke" },
-          { "test": "gpdb" },
-          { "test": "jdbc" },
-          { "test": "smoke", "fdw": "true" },
-          { "test": "gpdb", "fdw": "true" },
-          { "test": "jdbc", "fdw": "true" },
-          { "test": "ggdbssl", "fdw": "true", "ssl": "true" }
-        ]
-
-  integration-ggdb7-stable:
-    name: Integration on ggdb7-stable
-    uses: ./.github/workflows/integration-tests.yml
-    with:
-      image: greengagedb/ggdb7_ubuntu:7.4.0
-      version: '7'
-      release: stable
-      tests_matrix: |
-        [
-          { "test": "smoke" },
-          { "test": "gpdb" },
-          { "test": "jdbc" },
-          { "test": "smoke", "fdw": "true" },
-          { "test": "gpdb", "fdw": "true" },
-          { "test": "jdbc", "fdw": "true" },
-          { "test": "ggdbssl", "fdw": "true", "ssl": "true" }
-        ]
-
-  integration-ggdb7-devel:
-    name: Integration on ggdb7-devel
-    uses: ./.github/workflows/integration-tests.yml
-    with:
-      image: ghcr.io/greengagedb/greengage/ggdb7_ubuntu
-      version: '7'
-      release: devel
-      tests_matrix: |
-        [
-          { "test": "smoke" },
-          { "test": "gpdb" },
-          { "test": "jdbc" },
-          { "test": "smoke", "fdw": "true" },
-          { "test": "gpdb", "fdw": "true" },
-          { "test": "jdbc", "fdw": "true" },
-          { "test": "ggdbssl", "fdw": "true", "ssl": "true" }
-        ]
+          ghcr_token: ${{ secrets.ghcr_token }}
+          artifact_name: pxf-packages-${{ matrix.version }}-${{ matrix.release }}           # optional, defaults to deb-packages
+          # version: ${{ inputs.version }}    # optional, defaults empty
+          # package_name: greengage           # optional, defaults to repo name
+          # extensions: "deb ddeb"            # optional, space-separated list of extensions
